[project]
name = 'drain-stx'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stx-sweeper-test]
path = 'contracts/stx-sweeper.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
